// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// A class that exposes all Flutter Firebase options.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    }
    if (defaultTargetPlatform == TargetPlatform.linux) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:android:abcdef1234567890abcd',
    messagingSenderId: '123456789',
    projectId: 'crop-ai-dev',
    databaseURL: 'https://crop-ai-dev.firebaseio.com',
    storageBucket: 'crop-ai-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:ios:abcdef1234567890abcd',
    messagingSenderId: '123456789',
    projectId: 'crop-ai-dev',
    databaseURL: 'https://crop-ai-dev.firebaseio.com',
    storageBucket: 'crop-ai-dev.appspot.com',
    iosClientId: 'xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.cropai.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:windows:abcdef1234567890abcd',
    messagingSenderId: '123456789',
    projectId: 'crop-ai-dev',
    authDomain: 'crop-ai-dev.firebaseapp.com',
    databaseURL: 'https://crop-ai-dev.firebaseio.com',
    storageBucket: 'crop-ai-dev.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:linux:abcdef1234567890abcd',
    messagingSenderId: '123456789',
    projectId: 'crop-ai-dev',
    databaseURL: 'https://crop-ai-dev.firebaseio.com',
    storageBucket: 'crop-ai-dev.appspot.com',
  );
}

final defaultTargetPlatform = _getTargetPlatform();

TargetPlatform _getTargetPlatform() {
  if (kIsWeb) return TargetPlatform.android;
  return defaultTargetPlatform;
}
